### ISSUE TITLE
Tests refactor

### ISSUE THREAD

**Issue by noelsison** [KRGG/RRS#13]
@marc-lopez 
1. Why use `import django.test as django_test` instead of directly importing **TestCase**?
2. I think we should use reverse generated urls (`reverse('view:index')`) instead of hard coded ones unless we really want the url to be on that format and nothing else

I used the default [Django 1.7 tutorial](https://docs.djangoproject.com/en/1.7/intro/tutorial05/#testing-our-new-view) as reference to code style

**Comment by marc-lopez** [comment]
1. I used `import django.test as django_test` so that we can refer to this particular library multiple times (I imported django.test.Client and django.test.TestCase). As an alternative, I can use `from django.test import TestCase, Client`. Would this be more readable in your opinion?
2. I agree. Tried suggestion 2 with this: e4248f2121f13d02e16784201fb91d5fb5e3070b

**Comment by noelsison** [comment]
In `def a_test_function(self):`, **self** already contains the client variable: **self.client** that is recreated for each test so there is no need to instantiate a client each time.

Refer to [Default test client documentation](https://docs.djangoproject.com/en/1.7/topics/testing/tools/#default-test-client)

I think using specific imports is more readable. As a guideline, I propose we use imports in this order:
1. Specific imports: `from django.test import Client`
2. Named imports only when there is collision between the names of specific imports and/or the current file
3. Wildcard imports only when we are using all (or almost all of the many) classes inside the file to be imported

**Comment by marc-lopez** [comment]
Seconded

**Comment by noelsison** [comment]
The refactors look good. Added guideline to code style documentation.

**Comment by noelsison** [comment]
Close this issue when **refactor** branch is merged to dev

**Comment by marc-lopez** [comment]
Merged. Will create pull request to promote to master
