### ISSUE TITLE
Restore customer base template

### ISSUE THREAD

**Issue by noelsison** [KRGG/RRS#28]
Was removed on a previous merge

**Comment by marc-lopez** [comment]
Already restored in 863829835a78011c86fb62ba7d5e1aa11e7bd6ef

**Comment by noelsison** [comment]
**base.html** of customer templates is not yet restored

**Comment by marc-lopez** [comment]
**templates/customer/base.html** is now restored in d8b0d8be30d24b065170914982ce9bf4bbe91880
